name: Docker Image Build & Push

on:
  push:
    branches: [ "main", "feat*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Exec Submodule
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          submodules: true
      - 
        name: Configure git
        env:
          TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      -
        uses: actions/checkout@v3

      -
        name: Setup JAVA 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
  
      - 
        name: Clone Secrets
        run: git clone https://github.com/Ajou-Play/secrets-env.git
  
      - 
        name: Change Secrets
        run: mv secrets-env/application-local.yml src/main/resources/application-local.yml
        
      - 
        name: Log Secrets
        run: cat src/main/resources/application-local.yml | grep url

      - name: Clone OCI
        run: git clone https://github.com/Ajou-Play/oci-secrets.git

      - name: MKDIR OCI
        run: mkdir -p ~/ocikey

      - name: Move OCI
        run: cp oci-secrets/* ~/ocikey/

      - name: Log OCI
        run: cat ~/ocikey/config

      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Grant execute permission for gradlew
        run: chmod +x gradlew

      -
        name: Build with Gradle
        run: ./gradlew jib
